FROM ubuntu:16.04
MAINTAINER includeos.org
RUN \
  apt-get update && \
  apt-get install -y bc git lsb-release sudo
RUN cd ~ && pwd && \
  git clone https://github.com/hioa-cs/IncludeOS.git && \
  cd IncludeOS && \
  git checkout 5e2ea5be3e4ece2a844647e0f29ec26b5c52d613 && \
  git fetch --tags && \
  /bin/bash ./install.sh
